-- MySQL Script generated by MySQL Workbench
-- Thu Dec 21 16:29:42 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(45) NOT NULL,
  `cpf_cliente` VARCHAR(45) NOT NULL,
  `telefone_cliente` VARCHAR(15) NOT NULL,
  `senha_cliente` VARCHAR(45) NOT NULL,
  `login_cliente` VARCHAR(45) NOT NULL,
  `status_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`setor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`setor` (
  `id_setor` INT NOT NULL AUTO_INCREMENT,
  `descricao_setor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_setor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`livros` (
  `id_livros` INT NOT NULL AUTO_INCREMENT,
  `descricao_livro` VARCHAR(45) NOT NULL,
  `codigo_livros` VARCHAR(45) NOT NULL,
  `pag_livros` INT NOT NULL,
  `status_livro` VARCHAR(15) NOT NULL,
  `setor_id_setor` INT NOT NULL,
  PRIMARY KEY (`id_livros`),
  INDEX `fk_livros_setor1_idx` (`setor_id_setor` ASC),
  CONSTRAINT `fk_livros_setor1`
    FOREIGN KEY (`setor_id_setor`)
    REFERENCES `biblioteca`.`setor` (`id_setor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`emprestimo` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `data_inicio_emprestimo` DATE NOT NULL,
  `data_fim_emprestimo` DATE NOT NULL,
  `clientes_id_cliente` INT NOT NULL,
  `livros_id_livros` INT NOT NULL,
  PRIMARY KEY (`id_emprestimo`),
  INDEX `fk_emprestimo_clientes_idx` (`clientes_id_cliente` ASC),
  INDEX `fk_emprestimo_livros1_idx` (`livros_id_livros` ASC),
  CONSTRAINT `fk_emprestimo_clientes`
    FOREIGN KEY (`clientes_id_cliente`)
    REFERENCES `biblioteca`.`clientes` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_livros1`
    FOREIGN KEY (`livros_id_livros`)
    REFERENCES `biblioteca`.`livros` (`id_livros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`funcionario` (
  `id_funcionario` INT UNSIGNED NOT NULL,
  `nome_funcionario` VARCHAR(45) NOT NULL,
  `login_cliente` VARCHAR(45) NOT NULL,
  `senha_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
